apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 5m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
spec:
  interval: 5m0s
  url: https://flagger.app
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: console
spec:
  interval: 5m0s
  url: https://pluralsh.github.io/console
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bootstrap
spec:
  interval: 5m0s
  url: https://pluralsh.github.io/bootstrap
